export type ConfidenceLevel = "high" | "medium" | "low";

export type DataSourceType =
  | "manual"
  | "catalog"
  | "derived"
  | "heuristic"
  | "ai"
  | "external";

export type ConfidenceMeta = {
  confidence: ConfidenceLevel;
  source: DataSourceType;
  summary: string;
  reasons?: string[];
  caveat?: string;
};

export const confidenceMeta = {
  catalogRecord: {
    confidence: "high",
    source: "catalog",
    summary: "Stored vault data from the local seed record.",
    reasons: ["Seed name, breeder, type, and inventory are saved values rather than inferred estimates."],
  },
  rarity: {
    confidence: "medium",
    source: "derived",
    summary: "Rule-based rarity score from breeder, stock level, and lineage/name cues.",
    reasons: ["Remaining seed count is known, but breeder rarity and hype cues are weighted heuristics."],
  },
  terpeneProfile: {
    confidence: "low",
    source: "heuristic",
    summary: "Estimated from strain name and recognizable lineage/flavor cues.",
    caveat: "Not a lab terpene result or verified breeder profile.",
  },
  lineageSplit: {
    confidence: "low",
    source: "heuristic",
    summary: "Estimated indica/sativa lean from recognizable lineage words in the strain name.",
    caveat: "Treat as a rough planning lean, not a verified genetic percentage.",
  },
  cannabinoidPanel: {
    confidence: "low",
    source: "heuristic",
    summary: "Estimated cannabinoid ranges from name/lineage cues.",
    caveat: "Planning estimate only — not a certificate of analysis or lab result.",
  },
  yieldEstimate: {
    confidence: "low",
    source: "heuristic",
    summary: "Estimated from inferred vigor, structure, seed type, and grow-space assumptions.",
    caveat: "Actual yield depends heavily on phenotype, environment, training, and grower execution.",
  },
  advancedMetrics: {
    confidence: "low",
    source: "heuristic",
    summary: "Estimated from strain name, breeder, and lineage cues.",
    reasons: ["Flowering, resin, stretch, resistance, and ease values are planning signals."],
    caveat: "Confirm with real grow notes before making preservation decisions.",
  },
  keeperPriority: {
    confidence: "medium",
    source: "derived",
    summary: "Rule-based priority from scarcity, breeder value, seed type, and sought-after lineage cues.",
    caveat: "A low-priority line can still be worth keeping if the phenotype proves special.",
  },
  aiGenerated: {
    confidence: "low",
    source: "ai",
    summary: "Generated by AI using your vault data and the app's estimation engines as context.",
    caveat: "Use as advisory guidance; verify important cultivation decisions with your own observations.",
  },
} satisfies Record<string, ConfidenceMeta>;

export const getLineageConfidenceMeta = (name: string): ConfidenceMeta => {
  const hasExplicitCross = /×|\sx\s|\([^)]*(×|\sx\s)[^)]*\)/i.test(name);

  if (hasExplicitCross) {
    return {
      confidence: "high",
      source: "derived",
      summary: "Built from explicit cross notation written in the strain name.",
      reasons: ["The parser only expands parents that are visible in the name."],
    };
  }

  return {
    confidence: "low",
    source: "heuristic",
    summary: "Only partial lineage could be inferred from the visible strain name.",
    caveat: "Add explicit parent notation to improve lineage confidence.",
  };
};
